mappings:
  axes:
    - axes[0]
    - axes[1]
    - axes[3]
    - axes[2]
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  buttons:
    - buttons[10]
    - buttons[8]
    - buttons[9]
    - buttons[11]
    - max(axes[5], 0.0)
    - min(axes[4], 0.0) * -1.0
    - min(axes[5], 0.0) * -1.0
    - max(axes[4], 0.0)
    - buttons[6]
    - buttons[7]
    - buttons[4]
    - buttons[5]
    - buttons[1]
    - buttons[3]
    - buttons[2]
    - buttons[0]
    - buttons[12]
