- pose:
    position:
        x: 0.516944
        y: 0.017299
        z: 0
    orientation:
        x: 0
        y: 0
        z: -0.00483982
        w: 0.999988
- pose:
    position:
        x: 0.541473
        y: 0.0605326
        z: 0
    orientation:
        x: 0
        y: 0
        z: 0.999981
        w: -0.00612101
- pose:
    position:
        x: -0.0215682
        y: -0.000560613
        z: 0
    orientation:
        x: 0
        y: 0
        z: 0.999927
        w: -0.0120489
- pose:
    position:
        x: -0.0371395
        y: 0.0483101
        z: 0
    orientation:
        x: -0
        y: -0
        z: 0.0202621
        w: 0.999795
